update dependency recommendations
Note, this moves from aws 1.10.x to 1.11.x. In 1.11.x
the return type of `putMetricData` for the cloudwatch
client changed from `void` to `PutMetricDataResult`.
This causes a NoSuchMethodError is using 1.11.x with
a servo version built using 1.10.x or earlier.